# Models
DEFAULT_AMOUNT = 0
NAME_MAX_LENGTH = 100
PASSWORD_MIN_LENGTH = 3
STR_MIN_LENGTH = 1

# JWT
JWT_LIFETIME_SECONDS = 3600

# Google API

COLUMN_COUNT = 11
ROW_COUNT = 100
SHEET_ID = 0
TIME_FORMAT = '%Y/%m/%d %H:%M:%S'
